import localFont from "next/font/local";
import "./globals.css";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';

const theme = createTheme({
    colorScheme: 'light'
  /** Put your mantine theme override here */
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={` antialiased`}
        >
          <MantineProvider theme={theme} withGlobalStyles withNormalizeCSS >
            {children}
          </MantineProvider>
        </body>
    </html>
  );
}

